/** Polite, pre-defined answer for anything blocked (never generated by the model). */
import { formatText } from "../../domain/texts.js";
import { getLogger } from "../../logging.js";
import { textsOf, topicOf } from "../common.js";
import { ctxOf, type GraphContext, type NodeConfig } from "../context.js";
import type { ConversationState, Update } from "../state.js";

const log = getLogger("coach.graph.nodes.safe_reply");

export async function safeReply(state: ConversationState, config: NodeConfig): Promise<Update> {
  const ctx = ctxOf(config);
  const s = ctx.settings;
  const t = textsOf(state);
  const reason = state.blocked_reason || "unsupported";
  if (reason === "daily_limit" && !(await firstNotice(ctx, state.user_id))) {
    log.info("safe_reply", { reason, silent: true }); // told once today already
    return { kind: "blocked", blocked_reason: reason, outbound_texts: [] };
  }
  let template = t.blocked[reason] ?? (t.blocked.unsupported as string);
  if (reason === "low_confidence" && state.text) {
    template = t.heardRetry.replace("{heard}", [...state.text].slice(0, 200).join("")); // what was heard
  }
  const text = formatText(template, {
    topic: topicOf(state),
    max_chars: s.maxTextChars,
    max_seconds: s.maxAudioSeconds,
    limit: state.daily_limit || 0,
  });
  log.info("safe_reply", { reason });
  return { kind: "blocked", blocked_reason: reason, outbound_texts: [text] };
}

async function firstNotice(ctx: GraphContext, userId: number): Promise<boolean> {
  try {
    return await ctx.limits.firstLimitNotice(String(userId), ctx.config.timezone);
  } catch {
    return true; // Redis down: better a repeated answer than none
  }
}
